/**
 * HomeDashboard — grid of active library spaces with status, progress,
 * and quick-jump into the space detail view.
 *
 * Pinned spaces float to the top.  Archived spaces are hidden by
 * default (toggle in the header).  Each card can show an optional
 * cover image (uploaded or generated by Prax).
 *
 * Hierarchy note: this shows library **spaces**, not TeamWork
 * projects.  A TeamWork project is the outer tenant (e.g., "Prax")
 * and spaces are the groupings inside it ("Learn French", "Business",
 * "Q2 launch").  See docs/library.md for the full hierarchy.
 */
import { useState, useMemo } from 'react';
import { clsx } from 'clsx';
import {
  Star, Target, Calendar, Archive as ArchiveIcon,
  CheckCircle2, Pause, X, Plus, Layout, Loader2,
} from 'lucide-react';
import { useLibrary, useCreateLibrarySpace } from '@/hooks/useApi';
import type { LibrarySpace } from '@/hooks/useApi';
import { useUIStore } from '@/stores';
import { progressColor } from '@/utils/spaceTheme';

interface Props {
  isVisible: boolean;
  onClose: () => void;
  /** Called when the user clicks a space card — receives the space slug. */
  onOpenProject: (spaceSlug: string) => void;
}

export function HomeDashboard({ isVisible, onOpenProject }: Props) {
  const dark = useUIStore((s) => s.darkMode);
  const { data, isLoading } = useLibrary();
  const createSpace = useCreateLibrarySpace();
  const [showArchived, setShowArchived] = useState(false);
  const [creating, setCreating] = useState(false);
  const [newName, setNewName] = useState('');

  const spaces = useMemo<LibrarySpace[]>(() => {
    const all = data?.spaces ?? [];
    if (showArchived) return all;
    return all.filter((s) => (s.status ?? 'active') !== 'archived');
  }, [data, showArchived]);

  if (!isVisible) return null;

  const bg = dark ? 'bg-slate-900' : 'bg-white';
  const border = dark ? 'border-slate-700' : 'border-gray-200';
  const t1 = dark ? 'text-slate-100' : 'text-slate-900';
  const t2 = dark ? 'text-slate-400' : 'text-slate-500';
  const t3 = dark ? 'text-slate-500' : 'text-slate-400';

  return (
    <div className={clsx('flex-1 flex flex-col min-w-0', bg)}>
      <div className={clsx('px-6 py-4 border-b flex items-center gap-3', border)}>
        <Layout className={clsx('w-5 h-5', dark ? 'text-indigo-400' : 'text-indigo-600')} />
        <h2 className={clsx('text-xl font-bold flex-1', t1)}>Spaces</h2>
        <button
          onClick={() => setCreating(true)}
          className={clsx(
            'px-3 py-1.5 rounded-lg text-sm font-medium text-white',
            dark ? 'bg-indigo-600 hover:bg-indigo-500' : 'bg-indigo-600 hover:bg-indigo-500',
          )}
        >
          <Plus className="w-3.5 h-3.5 inline -mt-0.5 mr-1" />
          New Space
        </button>
        <button
          onClick={() => setShowArchived((v) => !v)}
          className={clsx(
            'text-xs px-2 py-1 rounded',
            dark ? 'text-slate-300 hover:bg-slate-800' : 'text-slate-600 hover:bg-gray-200',
          )}
        >
          {showArchived ? 'Hide archived' : 'Show archived'}
        </button>
      </div>

      <div className="flex-1 overflow-y-auto p-6">
        {/* Inline create form */}
        {creating && (
          <div className={clsx('mb-4 p-4 rounded-lg border flex items-center gap-3', border, dark ? 'bg-slate-800/60' : 'bg-gray-50')}>
            <input
              autoFocus
              placeholder="Space name (e.g., Learn French, Q2 Launch, Personal)"
              value={newName}
              onChange={(e) => setNewName(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === 'Enter' && newName.trim()) {
                  createSpace.mutate({ name: newName.trim() }, { onSuccess: () => { setNewName(''); setCreating(false); } });
                }
                if (e.key === 'Escape') { setNewName(''); setCreating(false); }
              }}
              className={clsx(
                'flex-1 px-3 py-2 rounded border text-sm outline-none',
                dark ? 'bg-slate-800 text-slate-100 border-slate-700 focus:border-indigo-500' : 'bg-white text-slate-900 border-gray-300 focus:border-indigo-500',
              )}
            />
            <button
              disabled={!newName.trim() || createSpace.isPending}
              onClick={() => {
                if (newName.trim()) createSpace.mutate({ name: newName.trim() }, { onSuccess: () => { setNewName(''); setCreating(false); } });
              }}
              className="px-3 py-2 rounded text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-500 disabled:opacity-40 inline-flex items-center gap-1.5"
            >
              {createSpace.isPending && <Loader2 className="w-3.5 h-3.5 animate-spin" />}
              {createSpace.isPending ? 'Creating…' : 'Create'}
            </button>
            <button
              disabled={createSpace.isPending}
              onClick={() => { setNewName(''); setCreating(false); }}
              className={clsx('p-1 rounded disabled:opacity-40', dark ? 'hover:bg-slate-700' : 'hover:bg-gray-200')}
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        )}

        {isLoading && <div className={clsx('text-sm', t2)}>Loading…</div>}
        {!isLoading && spaces.length === 0 && !creating && (
          <div className="flex flex-col items-center justify-center py-16 gap-3">
            <Layout className={clsx('w-14 h-14', t3)} />
            <p className={clsx('text-base font-medium', t1)}>No spaces yet</p>
            <p className={clsx('text-sm', t3)}>
              Spaces are where you organize your work — courses, projects, goals, life areas.
            </p>
            <button
              onClick={() => setCreating(true)}
              className="mt-2 px-4 py-2 rounded-lg text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-500"
            >
              <Plus className="w-4 h-4 inline -mt-0.5 mr-1" />
              Create your first space
            </button>
          </div>
        )}

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
          {spaces.map((space) => (
            <SpaceCard
              key={space.slug}
              space={space}
              dark={dark}
              onClick={() => onOpenProject(space.slug)}
            />
          ))}
        </div>
      </div>
    </div>
  );
}

// Gradient for the cover area — uses the space's theme_hue if set,
// otherwise falls back to a slug-hash-derived hue for visual stability.
function gradientFor(space: LibrarySpace, dark: boolean): string {
  let hue: number;
  if (space.theme_hue != null) {
    hue = space.theme_hue;
  } else {
    let h = 0;
    for (let i = 0; i < space.slug.length; i++) h = (h * 31 + space.slug.charCodeAt(i)) | 0;
    hue = Math.abs(h) % 360;
  }
  const hue2 = (hue + 30) % 360;
  // Keep it muted and classy — low saturation, appropriate lightness
  const sat = dark ? '30%' : '25%';
  const lit = dark ? '20%' : '85%';
  return `linear-gradient(135deg, hsl(${hue}, ${sat}, ${lit}) 0%, hsl(${hue2}, ${sat}, ${lit}) 100%)`;
}

function SpaceCard({
  space, dark, onClick,
}: { space: LibrarySpace; dark: boolean; onClick: () => void }) {
  const t1 = dark ? 'text-slate-100' : 'text-slate-900';
  const t2 = dark ? 'text-slate-400' : 'text-slate-500';
  const t3 = dark ? 'text-slate-500' : 'text-slate-400';
  const cardBg = dark ? 'bg-slate-800/60' : 'bg-gray-50';
  const border = dark ? 'border-slate-700' : 'border-gray-200';

  const status = space.status ?? 'active';
  const progress = space.progress_percent ?? 0;
  const kind = space.kind ?? '';
  const targetDate = space.target_date ?? '';
  const coverSrc = space.cover_image
    ? `/api/library/spaces/${encodeURIComponent(space.slug)}/cover?t=${space.cover_image}`
    : null;

  return (
    <div
      onClick={onClick}
      className={clsx(
        'rounded-lg border cursor-pointer transition-all overflow-hidden',
        cardBg, border,
        dark ? 'hover:bg-slate-800 hover:border-indigo-500/50' : 'hover:bg-white hover:border-indigo-400 hover:shadow-sm',
      )}
    >
      {/* Cover image — real image if set, else theme-aware gradient */}
      <div
        className="h-24 w-full relative"
        style={coverSrc ? undefined : { background: gradientFor(space, dark) }}
      >
        {coverSrc && (
          <img
            src={coverSrc}
            alt={`Cover for ${space.name}`}
            className="w-full h-full object-cover"
          />
        )}
        {space.pinned && (
          <Star className="absolute top-2 right-2 w-4 h-4 text-amber-300 fill-amber-300 drop-shadow" />
        )}
      </div>

      <div className="p-4">
        <div className="flex items-start justify-between gap-2 mb-2">
          <h3 className={clsx('text-sm font-semibold truncate flex-1', t1)}>{space.name}</h3>
          <StatusPill status={status} dark={dark} />
        </div>

        <div className="flex items-center gap-2 flex-wrap mb-3 min-h-[18px]">
          {kind && (
            <span className={clsx(
              'text-xs px-1.5 py-0.5 rounded',
              dark ? 'bg-slate-700 text-slate-300' : 'bg-gray-200 text-slate-700',
            )}>
              {kind}
            </span>
          )}
          {targetDate && (
            <span className={clsx('text-xs flex items-center gap-0.5', t3)}>
              <Calendar className="w-3 h-3" /> {targetDate.slice(0, 10)}
            </span>
          )}
        </div>

        {space.description && (
          <p className={clsx('text-xs mb-3 line-clamp-2', t2)}>{space.description}</p>
        )}

        {/* Progress bar — shown when there's progress data */}
        <div className="space-y-1">
          <div className="flex items-center justify-between text-xs">
            <span className={t3}>
              {space.notebook_count ?? 0} notebook{space.notebook_count === 1 ? '' : 's'}
            </span>
            {progress > 0 && <span className={t2}>{progress}%</span>}
          </div>
          <div className={clsx('h-1 rounded-full overflow-hidden', dark ? 'bg-slate-700' : 'bg-gray-200')}>
            <div
              className="h-full rounded-full transition-all"
              style={{ width: `${progress}%`, backgroundColor: progressColor(space.theme_hue, dark) }}
            />
          </div>
        </div>
      </div>
    </div>
  );
}

function StatusPill({ status, dark }: { status: string; dark: boolean }) {
  const styles: Record<string, { icon: typeof Target; color: string }> = {
    active: {
      icon: Target,
      color: dark ? 'bg-emerald-900/30 text-emerald-400' : 'bg-emerald-50 text-emerald-700',
    },
    paused: {
      icon: Pause,
      color: dark ? 'bg-amber-900/30 text-amber-400' : 'bg-amber-50 text-amber-700',
    },
    completed: {
      icon: CheckCircle2,
      color: dark ? 'bg-indigo-900/30 text-indigo-400' : 'bg-indigo-50 text-indigo-700',
    },
    archived: {
      icon: ArchiveIcon,
      color: dark ? 'bg-slate-700 text-slate-400' : 'bg-gray-100 text-slate-500',
    },
  };
  const { icon: Icon, color } = styles[status] ?? styles.active;
  return (
    <span className={clsx('text-xs px-1.5 py-0.5 rounded flex items-center gap-1 shrink-0', color)}>
      <Icon className="w-3 h-3" />
      {status}
    </span>
  );
}
